// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoBoard.Infrastructure.Data;

#nullable disable

namespace NeoBoard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626162928_AddCommunicationsSystem")]
    partial class AddCommunicationsSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NeoBoard.Domain.Entities.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ispublished");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publishedat");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_announcements");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_announcements_authorid");

                    b.ToTable("announcements");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.AnnouncementRead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AnnouncementId")
                        .HasColumnType("char(36)")
                        .HasColumnName("announcementid");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("readat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_announcementreads");

                    b.HasIndex("AnnouncementId")
                        .HasDatabaseName("ix_announcementreads_announcementid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_announcementreads_userid");

                    b.ToTable("announcementreads");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assetcode");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assignedtechnicianid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Custodian")
                        .HasColumnType("longtext")
                        .HasColumnName("custodian");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("invoicenumber");

                    b.Property<DateTime?>("LastMaintenance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmaintenance");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<int>("MaintenanceIntervalMonths")
                        .HasColumnType("int")
                        .HasColumnName("maintenanceintervalmonths");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("longtext")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchasedate");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("serialnumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Supplier")
                        .HasColumnType("longtext")
                        .HasColumnName("supplier");

                    b.Property<string>("TechnicalSpecs")
                        .HasColumnType("longtext")
                        .HasColumnName("technicalspecs");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTime?>("WarrantyExpiration")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("warrantyexpiration");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int")
                        .HasColumnName("warrantymonths");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("ix_assets_assignedtechnicianid");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.AssetHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assetid");

                    b.Property<int?>("BatteryCycleCount")
                        .HasColumnType("int")
                        .HasColumnName("batterycyclecount");

                    b.Property<int?>("BatteryHealthPercentage")
                        .HasColumnType("int")
                        .HasColumnName("batteryhealthpercentage");

                    b.Property<int?>("BulbHoursUsed")
                        .HasColumnType("int")
                        .HasColumnName("bulbhoursused");

                    b.Property<DateTime?>("EstimatedReplacementDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("estimatedreplacementdate");

                    b.Property<string>("HealthNotes")
                        .HasColumnType("longtext")
                        .HasColumnName("healthnotes");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("healthstatus");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmaintenancedate");

                    b.Property<int>("MaintenanceCycleDays")
                        .HasColumnType("int")
                        .HasColumnName("maintenancecycledays");

                    b.Property<DateTime?>("NextScheduledMaintenance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("nextscheduledmaintenance");

                    b.HasKey("Id")
                        .HasName("pk_assethealths");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_assethealths_assetid");

                    b.ToTable("assethealths");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.BorrowItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("actualreturndate");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assetid");

                    b.Property<Guid>("BorrowRequestId")
                        .HasColumnType("char(36)")
                        .HasColumnName("borrowrequestid");

                    b.Property<string>("ConditionOnBorrow")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("conditiononborrow");

                    b.Property<string>("ConditionOnReturn")
                        .HasColumnType("longtext")
                        .HasColumnName("conditiononreturn");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ToolsetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("toolsetid");

                    b.HasKey("Id")
                        .HasName("pk_borrowitems");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_borrowitems_assetid");

                    b.HasIndex("BorrowRequestId")
                        .HasDatabaseName("ix_borrowitems_borrowrequestid");

                    b.HasIndex("ToolsetId")
                        .HasDatabaseName("ix_borrowitems_toolsetid");

                    b.ToTable("borrowitems");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.BorrowRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("approvedbyid");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("evidencephotourl");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expectedreturndate");

                    b.Property<string>("Note")
                        .HasColumnType("longtext")
                        .HasColumnName("note");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("longtext")
                        .HasColumnName("previoushash");

                    b.Property<string>("Purpose")
                        .HasColumnType("longtext")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requestdate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("studentid");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("longtext")
                        .HasColumnName("transactionhash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_borrowrequests");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_borrowrequests_approvedbyid");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_borrowrequests_studentid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_borrowrequests_userid");

                    b.ToTable("borrowrequests");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext")
                        .HasColumnName("contenttype");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .HasColumnType("longtext")
                        .HasColumnName("entitytype");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("filename");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("filesizebytes");

                    b.Property<string>("OriginalName")
                        .HasColumnType("longtext")
                        .HasColumnName("originalname");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storagepath");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("uploadedbyid");

                    b.HasKey("Id")
                        .HasName("pk_fileattachments");

                    b.HasIndex("UploadedById")
                        .HasDatabaseName("ix_fileattachments_uploadedbyid");

                    b.ToTable("fileattachments");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ActionTaken")
                        .HasColumnType("longtext")
                        .HasColumnName("actiontaken");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assetid");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("char(36)")
                        .HasColumnName("assignedtechnicianid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EvidencePhotoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("evidencephotourl");

                    b.Property<DateTime?>("MaintenanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("maintenancedate");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduleddate");

                    b.Property<string>("SparePartsUsed")
                        .HasColumnType("longtext")
                        .HasColumnName("sparepartsused");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("totalcost");

                    b.Property<string>("VerificationResult")
                        .HasColumnType("longtext")
                        .HasColumnName("verificationresult");

                    b.HasKey("Id")
                        .HasName("pk_maintenancetickets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_maintenancetickets_assetid");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("ix_maintenancetickets_assignedtechnicianid");

                    b.ToTable("maintenancetickets");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("referenceid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_userid");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.PostComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("authorid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<Guid>("PostId")
                        .HasColumnType("char(36)")
                        .HasColumnName("postid");

                    b.HasKey("Id")
                        .HasName("pk_postcomments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_postcomments_authorid");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_postcomments_postid");

                    b.ToTable("postcomments");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isrevoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_refreshtokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refreshtokens_userid");

                    b.ToTable("refreshtokens");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ClassName")
                        .HasColumnType("longtext")
                        .HasColumnName("classname");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isblocked");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("studentcode");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.ToTable("students");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("creatorid");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("endsat");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startsat");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_surveys");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_surveys_creatorid");

                    b.ToTable("surveys");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isrequired");

                    b.Property<string>("Options")
                        .HasColumnType("longtext")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("questiontext");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("questiontype");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sortorder");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("surveyid");

                    b.HasKey("Id")
                        .HasName("pk_surveyquestions");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_surveyquestions_surveyid");

                    b.ToTable("surveyquestions");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_surveyresponses");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_surveyresponses_questionid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_surveyresponses_userid");

                    b.ToTable("surveyresponses");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.TimelinePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("authorid");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int")
                        .HasColumnName("commentcount");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("imageurl");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ispublished");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int")
                        .HasColumnName("likecount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_timelineposts");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_timelineposts_authorid");

                    b.ToTable("timelineposts");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Toolset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int")
                        .HasColumnName("availablequantity");

                    b.Property<string>("Code")
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Custodian")
                        .HasColumnType("longtext")
                        .HasColumnName("custodian");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("ItemsDetail")
                        .HasColumnType("longtext")
                        .HasColumnName("itemsdetail");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastmaintenancedate");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchasedate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Supplier")
                        .HasColumnType("longtext")
                        .HasColumnName("supplier");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int")
                        .HasColumnName("totalquantity");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("int")
                        .HasColumnName("warrantymonths");

                    b.HasKey("Id")
                        .HasName("pk_toolsets");

                    b.ToTable("toolsets");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("avatarurl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Department")
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fullname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isactive");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lastloginat");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passwordhash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updatedat");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdat");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ipaddress");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_useractivities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_useractivities_userid");

                    b.ToTable("useractivities");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "Author")
                        .WithMany("Announcements")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_announcements_users_authorid");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.AnnouncementRead", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.Announcement", "Announcement")
                        .WithMany("Reads")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcementreads_announcements_announcementid");

                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany("Reads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_announcementreads_users_userid");

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Asset", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_users_assignedtechnicianid");

                    b.Navigation("AssignedTechnician");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.AssetHealth", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.Asset", "Asset")
                        .WithOne("Health")
                        .HasForeignKey("NeoBoard.Domain.Entities.AssetHealth", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assethealths_assets_assetid");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.BorrowItem", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.Asset", "Asset")
                        .WithMany("BorrowItems")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_borrowitems_assets_assetid");

                    b.HasOne("NeoBoard.Domain.Entities.BorrowRequest", "BorrowRequest")
                        .WithMany("Items")
                        .HasForeignKey("BorrowRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_borrowitems_borrowrequests_borrowrequestid");

                    b.HasOne("NeoBoard.Domain.Entities.Toolset", "Toolset")
                        .WithMany("BorrowItems")
                        .HasForeignKey("ToolsetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_borrowitems_toolsets_toolsetid");

                    b.Navigation("Asset");

                    b.Navigation("BorrowRequest");

                    b.Navigation("Toolset");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.BorrowRequest", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_borrowrequests_users_approvedbyid");

                    b.HasOne("NeoBoard.Domain.Entities.Student", "Student")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_borrowrequests_students_studentid");

                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_borrowrequests_users_userid");

                    b.Navigation("ApprovedBy");

                    b.Navigation("Student");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.FileAttachment", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "UploadedBy")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UploadedById")
                        .HasConstraintName("fk_fileattachments_users_uploadedbyid");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.MaintenanceTicket", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenancetickets_assets_assetid");

                    b.HasOne("NeoBoard.Domain.Entities.User", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("AssignedTechnicianId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_maintenancetickets_users_assignedtechnicianid");

                    b.Navigation("Asset");

                    b.Navigation("AssignedTechnician");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.PostComment", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postcomments_users_authorid");

                    b.HasOne("NeoBoard.Domain.Entities.TimelinePost", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postcomments_timelineposts_postid");

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtokens_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Survey", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "Creator")
                        .WithMany("CreatedSurveys")
                        .HasForeignKey("CreatorId")
                        .HasConstraintName("fk_surveys_users_creatorid");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.SurveyQuestion", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveyquestions_surveys_surveyid");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.SurveyResponse", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.SurveyQuestion", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveyresponses_surveyquestions_questionid");

                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany("SurveyResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_surveyresponses_users_userid");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.TimelinePost", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_timelineposts_users_authorid");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("NeoBoard.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_useractivities_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Announcement", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Asset", b =>
                {
                    b.Navigation("BorrowItems");

                    b.Navigation("Health");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.BorrowRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Student", b =>
                {
                    b.Navigation("BorrowRequests");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.SurveyQuestion", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.TimelinePost", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.Toolset", b =>
                {
                    b.Navigation("BorrowItems");
                });

            modelBuilder.Entity("NeoBoard.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Announcements");

                    b.Navigation("Comments");

                    b.Navigation("CreatedSurveys");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Reads");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SurveyResponses");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
